# Generated by Django 4.2.2 on 2023-06-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=' ', max_length=250)),
                ('description', models.TextField()),
                ('dateAdded', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
